export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const VALIDATE_ERROR = 'VALIDATE_ERROR';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DESTROY_PROJECT = 'DESTROY_PROJECT';
